### ISSUE TITLE
OAuth Client-Server

### ISSUE THREAD

**Issue by ahmedAbouismail** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#18]
i finished building the authorization server and i'm trying now to build an oauth client-side server. i set the Configuration of the client server as follows:
```
app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost
  auth-server: localhost



eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

spring:
  security:
    oauth2:
      client:
        registration:
          writer-client-oidc:
            provider: spring
            client-id: writer
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "https://localhost:8443/login/oauth2/code/writer-client-oidc"
            scope: openid
            client-name: writer-client-oidc
          writer-client-authorization-code:
            provider: spring
            client-id: writer
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "https://localhost:8443/authorized"
            scope: chart:write
            client-name: writer-client-authorization-code
          writer-client-client-credentials:
            provider: spring
            client-id: writer
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: chart:write
            client-name: writer-client-client-credentials
        provider:
          spring:
            issuer-uri: http://${app.auth-server}:9999
```

I expected that with this Configuration i will be able to connect to the authorization server but i got that error:

```
Caused by: java.lang.IllegalArgumentException: Unable to resolve Configuration with the provided Issuer of "http://auth-server:9999"
2022-06-26T08:04:16.064768700Z 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.getBuilder(ClientRegistrations.java:221) ~[spring-security-oauth2-client-5.4.5.jar:5.4.5]
2022-06-26T08:04:16.064774200Z 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.fromIssuerLocation(ClientRegistrations.java:145) ~[spring-security-oauth2-client-5.4.5.jar:5.4.5]
2022-06-26T08:04:16.064779100Z 	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getBuilderFromIssuerIfPossible(OAuth2ClientPropertiesRegistrationAdapter.java:83) ~[spring-boot-autoconfigure-2.4.4.jar:2.4.4]
2022-06-26T08:04:16.064786000Z 	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistration(OAuth2ClientPropertiesRegistrationAdapter.java:59) ~[spring-boot-autoconfigure-2.4.4.jar:2.4.4]
2022-06-26T08:04:16.064796800Z 	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.lambda$getClientRegistrations$0(OAuth2ClientPropertiesRegistrationAdapter.java:53) ~[spring-boot-autoconfigure-2.4.4.jar:2.4.4]
2022-06-26T08:04:16.064826800Z 	at java.base/java.util.HashMap.forEach(Unknown Source) ~[na:na]
2022-06-26T08:04:16.064833700Z 	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistrations(OAuth2ClientPropertiesRegistrationAdapter.java:52) ~[spring-boot-autoconfigure-2.4.4.jar:2.4.4]
2022-06-26T08:04:16.064838900Z 	at org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientRegistrationRepositoryConfiguration.clientRegistrationRepository(OAuth2ClientRegistrationRepositoryConfiguration.java:49) ~[spring-boot-autoconfigure-2.4.4.jar:2.4.4]
2022-06-26T08:04:16.064844200Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2022-06-26T08:04:16.064849100Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2022-06-26T08:04:16.064853900Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2022-06-26T08:04:16.064858600Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2022-06-26T08:04:16.064863600Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.5.jar:5.3.5]
2022-06-26T08:04:16.064868500Z 	... 80 common frames omitted
2022-06-26T08:04:16.064873300Z Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://auth-server:9999/.well-known/openid-configuration": auth-server; nested exception is java.net.UnknownHostException: auth-server
2022-06-26T08:04:16.064905700Z 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785) ~[spring-web-5.3.5.jar:5.3.5]
2022-06-26T08:04:16.064910900Z 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:670) ~[spring-web-5.3.5.jar:5.3.5]
2022-06-26T08:04:16.064916100Z 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.lambda$oidc$0(ClientRegistrations.java:156) ~[spring-security-oauth2-client-5.4.5.jar:5.4.5]
2022-06-26T08:04:16.064921000Z 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.getBuilder(ClientRegistrations.java:209) ~[spring-security-oauth2-client-5.4.5.jar:5.4.5]
2022-06-26T08:04:16.064928000Z 	... 92 common frames omitted
2022-06-26T08:04:16.064932900Z Caused by: java.net.UnknownHostException: auth-server
2022-06-26T08:04:16.064938500Z 
```
the configuration class:
```
@Configuration
public class WebClientConfig {

    @Bean
    @LoadBalanced
    WebClient webClient(OAuth2AuthorizedClientManager authorizedClientManager) {
        ServletOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
                new ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
        return WebClient.builder()
                .apply(oauth2Client.oauth2Configuration())
                .build();
    }

    @Bean
    OAuth2AuthorizedClientManager authorizedClientManager(
            ClientRegistrationRepository clientRegistrationRepository,
            OAuth2AuthorizedClientRepository authorizedClientRepository) {

        OAuth2AuthorizedClientProvider authorizedClientProvider =
                OAuth2AuthorizedClientProviderBuilder.builder()
                        .authorizationCode()
                        .refreshToken()
                        .clientCredentials()
                        .build();
        DefaultOAuth2AuthorizedClientManager authorizedClientManager = new DefaultOAuth2AuthorizedClientManager(
                clientRegistrationRepository, authorizedClientRepository);
        authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

        return authorizedClientManager;
    }
}
```
```
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    WebSecurityCustomizer webSecurityCustomizer() {
        return (web) -> web.ignoring().antMatchers("/webjars/**");
    }


    @Bean
    SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
                .authorizeRequests(authorizeRequests ->
                        authorizeRequests.anyRequest().authenticated()
                )
                .oauth2Login(oauth2Login ->
                        oauth2Login.loginPage("/oauth2/authorization/writer-client-oidc"))
                .oauth2Client(withDefaults());
        return http.build();
    }

}
```

does anyone know why i get this error?

**Comment by ahmedAbouismail** [comment]
i found the solution in that link
 https://tjtelan.com/blog/how-to-link-multiple-docker-compose-via-network/
